use_frameworks!

target 'SWAlertViewController_Example' do
  pod 'SWAlertViewController', :path => '../'

  target 'SWAlertViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
