platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

inhibit_all_warnings!

target 'SWAlertViewController_Example' do
#  pod 'SWAlertViewController', :path => '../'
#
#  target 'SWAlertViewController_Tests' do
#    inherit! :search_paths
#
#   pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
	
	pod 'SWAlertViewController'
end
